langCorrect/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('journals/', views.journal, name='journal'),
    path('prompts/', views.prompts, name='prompts'),
    path('<str:post_title>/make_corrections/', views.corrections, name='corrections'),
    path('signup/', views.signup, name='signup'),
    path('journals/~create/', views.CreatePost.as_view(), name='creating_post'),
    path('journals/<str:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('users/<str:username>/', views.profile, name='profile'),
    path('languages/', views.LanguageList.as_view(), name='profile_update'),
    path('languages/<str:language>/delete', views.DeleteLanguage.as_view(), name='language_delete')
]

langCorrectClone/urls.py
from django.contrib import admin
from django.urls import path, include
from langCorrect import urls as lc_urls
from users import urls as u_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(lc_urls))
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:username>/', views.profile, name="profile"),
]

langCorrect/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Language(models.Model):
    name = models.CharField(max_length=20, primary_key=True, unique=True)

    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    male = "Мужской"
    female = "Женский"
    other = "Другой"
    unknown = "Предпочитаю не указывать"

    username = models.CharField(max_length=20, primary_key=True, unique=True)
    gender_choice = ((male, "Мужской"), (female, "Женский"), (other, "Другой"), (unknown, "Предпочитаю не указывать"))
    native_language = models.ForeignKey(Language, on_delete=models.PROTECT, related_name="native_language", null=True)
    gender = models.CharField(choices=gender_choice, default=unknown)


class LanguageLevel(models.Model):
    level_choices = [("A2", "Новичок"), ("A1", "Элементарный"), ("B2", "Средний"), ("B1", "Выше среднего"),
                     ("C2", "Продвинутый"), ("C1", "Опытный")]
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    student = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    level = models.CharField(max_length=20, choices=level_choices, default="Новичок")

    def __str__(self):
        return self.student.username + " knows " + self.language.name + " at " + self.level + " level"


class Post(models.Model):
    male = "Мужской"
    female = "Женский"
    other = "Другой"
    unknown = "Предпочитаю не указывать"
    gender_choice = ((male, "Мужской"), (female, "Женский"), (other, "Другой"), (unknown, "Предпочитаю не указывать"))

    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, primary_key=True, unique=True)
    verbose_title = models.CharField(max_length=20)
    text = models.TextField()
    native_text = models.TextField(null=True)
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    gender = models.CharField(choices=gender_choice, default=unknown)
    #permission = models.CharField(choices=(('all', 'Видимо всем'), ('signedIn', 'Видно только зарегистрированный пользователям')))
    correctionsQuantity = models.IntegerField(default=0)
    creation_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})


class Correction(models.Model):
    # def __init__(self, *args, **kwargs):
    #     super(Correction, self).__init__(*args, **kwargs)
    #     self.original = self.post.text

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    commentary = models.TextField(null=True)
    # corrected = models.TextField()


class Sentence(models.Model):
    original = models.TextField()
    text = models.TextField(default='')
    commentary = models.TextField(default='')
    isCorrect = models.BooleanField(default=False)
    correction = models.ForeignKey(Correction, on_delete=models.CASCADE)

    def __str__(self):
        if self.text != '':
            return self.text
        else:
            return 'Все правильно'

langCorrect/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Post, Language, Sentence


# class CorrectionForm(forms):
#     def __init__(self, *args, **kwargs):
#         num_fields = kwargs.pop('num_fields', 1)  # Получаем число полей из аргументов
#         super().__init__(*args, **kwargs)
#
#         # Добавляем поля формы в зависимости от переданного числа
#         for i in range(num_fields):
#             field_name = f'field_{i}'
#             self.fields[field_name] = forms.CharField(label=f'Field {i}')


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2", "gender", "native_language")


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")


class LanguageForm(forms.Form):
    level_choices = [("A2", "Новичок"), ("A1", "Элементарный"), ("B2", "Средний"), ("B1", "Выше среднего"),
                     ("C2", "Продвинутый"), ("C1", "Опытный")]

    name = forms.ModelChoiceField(queryset=Language.objects.all().values_list('name', flat=True), empty_label='------------')
    level = forms.ChoiceField(choices=level_choices)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'native_text', 'language', 'gender']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     user = kwargs.pop('user', None)
    #     if user:
    #         self.fields['language'].queryset = user.languagelevel_set


class CorrectSentence(forms.ModelForm):
    text = forms.CharField(required=False)  # Устанавливаем required=False для поля text
    commentary = forms.CharField(required=False)  # Устанавливаем required=False для поля commentary

    class Meta:
        model = Sentence
        fields = ['text', 'commentary']

langCorrect/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django import forms
from .models import Post, LanguageLevel, Correction, Sentence, CustomUser
from django.views.generic.detail import DetailView
from .forms import CustomUserCreationForm, LanguageForm, Language, CorrectSentence


def signup(request):
    if request.method == 'POST':
        user_form = CustomUserCreationForm(request.POST)
        language_form = LanguageForm(request.POST)
        if user_form.is_valid() and language_form.is_valid():
            print('Досюда работает')
            user = user_form.save()
            language_name = language_form.cleaned_data['name']
            language = Language.objects.filter(name=language_name).first()
            level = language_form.cleaned_data['level']
            new_language = LanguageLevel.objects.create(student=user, language=language, level=level)
            new_language.save()
            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('journal')  # Перенаправление на главную страницу после успешной регистрации
    else:
        user_form = CustomUserCreationForm()
        language_form = LanguageForm()
    return render(request, 'langCorrect/signup.html', {'user_form': user_form, 'language_form': language_form})


def journal(request):
    posts = Post.objects.all()
    return render(request, 'langCorrect/journal.html', context={'posts': posts})


class CreatePost(CreateView):
    model = Post
    fields = ['title', 'text', 'native_text', 'language', 'gender']
    #form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        print(self.request.user)
        form = super().get_form(form_class)
        print(LanguageLevel.objects.filter(student=self.request.user).values_list('language', flat=True))
        # print('Выше должен быть список языков')
        language_names = LanguageLevel.objects.filter(student=self.request.user).values_list('language_id', flat=True)
        form.fields['language'].queryset = Language.objects.filter(pk__in=language_names)
        return form


class PostDetail(DetailView):
    model = Post  # Указываем модель, которую мы хотим отобразить
    template_name = 'langCorrect/postDetail.html'  # Указываем имя шаблона, который мы будем использовать
    context_object_name = 'post'

    def get_queryset(self):
        post_title = self.kwargs.get('pk')
        return Post.objects.filter(title=post_title)


def prompts(request):
    return HttpResponse('<h1>Промпты</h1>')


def corrections(request, post_title):
    if request.method == 'POST':
        content_len = len(Post.objects.all().filter(title=post_title).first().text.split('.'))
        content = Post.objects.all().filter(title=post_title).first().text.split('.')
        new_correction = Correction.objects.create(post=Post.objects.all().filter(title=post_title).first(), author=request.user)
        new_correction.save()
        for i in range(content_len):
            new_sentence = Sentence.objects.create(correction=new_correction)
            new_sentence.original = content[i]
            if request.POST.getlist('text')[i]:
                new_sentence.text = request.POST.getlist('text')[i]
            else:
                new_sentence.isCorrect = True
            if new_sentence.text == new_sentence.original:
                new_sentence.isCorrect = True
            if request.POST.getlist('commentary')[i]:
                new_sentence.commentary = request.POST.getlist('commentary')[i]
            new_sentence.save()
        return redirect('journal')

    else:
        content = Post.objects.all().filter(title=post_title).first().text.split('.')
        forms = []
        for sentence in content:
            new_tuple = (sentence, CorrectSentence())
            print(tuple)
            forms.append(new_tuple)

        return render(request, 'langCorrect/corrections.html', context={'content': content, 'form': forms})


def profile(request, username):
    user = CustomUser.objects.get(username=username)
    languages = LanguageLevel.objects.filter(student=user)
    posts = user.post_set.all()
    return render(request, 'langCorrect/profile.html', context={'user': user, 'languages': languages,                                                             'posts': posts})


class LanguageList(ListView):
    model = LanguageLevel
    context_object_name = 'languageLevels'
    template_name = 'langCorrect/languageList.html'

    def get_queryset(self):
        return LanguageLevel.objects.filter(student=self.request.user)


class DeleteLanguage(DeleteView):
    model = LanguageLevel
    template_name = 'langCorrect/deleteLanguage.html'
    context_object_name = 'language'

langCorrect/templates/langCorrect/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Навбар</title>
<style>
/* Стили для навбара */
.navbar {
  display:flex;
  justify-content: center;
  align-items: center;
  background-color: #333; /* Цвет фона */
  overflow: hidden;
  margin-bottom:10px;
}

/* Стили для ссылок в навбаре */
.navbar a {
  display: block;
  color: #f2f2f2; /* Цвет текста */
  text-align: center;
  padding: 25px 25px; /* Отступы */
  text-decoration: none; /* Убираем подчеркивание */
  font-size:20px;
}


/* При наведении курсора на ссылку */
.navbar a:hover {
  background-color: #ddd; /* Цвет фона */
  color: black; /* Изменяем цвет текста */

}

 #write{
   text-align:right;
}
</style>
</head>
<body>

<!-- Навбар -->
<div class="navbar">
  <a href="#">Начало</a>
  <a href="#">Подсказки</a>
  <a href="#">Сообщество</a>
  <a id="write" href="{% url 'creating_post' %}">Написать</a>
</div>
<div>

</div>
{% block content %}
{% endblock content %}
</body>
</html>

langCorrect/templates/langCorrect/corrections.html
<style>
.wrapper {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.sentence {
    flex-grow: 1;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

.correctWindow {
    flex-grow: 1;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
    display: None
}

.footer {
    display: flex;
    justify-content: flex-end;
    align-items: center;
}

.correct,
.edit {
    padding: 5px 10px;
    margin-left: 10px;
    border: 1px solid #ccc;
    border-radius: 3px;
    background-color: #f9f9f9;
    cursor: pointer;
}

.correct:hover,
.edit:hover {
    background-color: #eaeaea;
}
</style>
{% extends 'langCorrect/base.html' %}
{% load static %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for sentence in form %}
            <div class="wrapper">
                <div class="sentence">
                    {{ sentence.0 }}
                </div>
                <div class="correctWindow">
                    {{ sentence.1 }}
                </div>
                <div class="footer">
                    <button type="button" class="correct">Верно</button>
                    <button type="button" class="edit">Исправить</button>
                </div>
            </div>
        {% endfor %}
        <button type="submit">Отправить</button>
        </form>

    <script src="{% static 'langCorrect/script.js' %}"></script>
{% endblock %}

langCorrect/templates/langCorrect/deleteLanguage.html
{% extends 'langCorrect/base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h2>Вы уверены, что хотите удалить {{ language.language }} ({{ language.level }}) из вашего списка языков</h2>
        <div>
            <button type="submit">Удалить</button>
            <button>Отмена</button>
        </div>
    </form>
{% endblock content %}

langCorrect/templates/langCorrect/journal.html
<style>
.post {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 20px;
    background-color: #f9f9f9;
}

.post-head {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
}

.post-head a {
    text-decoration: none;
    color: #333;
}

.timestamp {
    margin: 0;
    color: #666;
}

.post-body {
    margin-bottom: 10px;
}

.title {
    margin: 0;
    font-size: 20px;
}

.content {
    margin: 0;
    color: #555;
}

.post-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.post-footer span {
    color: #777;
}

.correct-link {
    text-decoration: none;
    color: blue;
}
</style>
{% extends 'langCorrect/base.html' %}
{% block content %}

    {% for post in posts %}
    <div class="post">
        <div class="post-head">
            <a href="{% url 'profile' post.author.username %}" class="author">{{ post.author.username }}</a>
            <p class="timestamp">{{ post.creation_timestamp | date:"j F Y г." }}</p>
        </div>
        <div class="post-body">
            <h2 class="title">{{ post.verbose_title }}</h2>
            <h2 class="title">{{ post.title }}</h2>
            <p class="content">{{ post.text }}</p>
        </div>
        <div class="post-footer">
            <span class="language">{{ post.language }}</span>
            <span class="corrections">Число исправлений: {{ post.correctionsQuantity }}</span>
            <a href="{% url 'corrections' post.title %}" class="correct-link">Исправить</a>
        </div>
    </div>
    {% endfor %}
{% endblock content %}

langCorrect/templates/langCorrect/languageList.html
{% extends 'langCorrect/base.html' %}

{% block content %}

    <table border="1">
        <tr rowspan="3">
            <th>Язык</th>
            <th>Уровень</th>
            <th>Действия</th>
        </tr>
    {% for languageLevel in languageLevels %}
        <tr rowspan="3">
            <td>{{ languageLevel.language }}</td>
            <td>{{ languageLevel.level }}</td>
            <td><a href="{% url 'language_delete' languageLevel.language %}"><button>Удалить</button></a>
                <button>Редактировать</button>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock content %}

langCorrect/templates/langCorrect/postDetail.html
<style>
.post {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-bottom: 20px;
    padding: 10px;
}

.head {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.head a {
    text-decoration: none;
    color: #333;
}

.timestamp {
    margin: 0;
    color: #999;
}

.body {
    margin-bottom: 10px;
}

.title {
    margin: 0;
    font-size: 20px;
}

.text {
    margin: 0;
    color: #666;
}

.footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.footer span {
    color: #999;
}

.correct {
    text-decoration: none;
    color: blue;
}

.corrections {
    margin-top: 20px;
}

.corrections h3 {
    margin: 0 0 10px;
}

.correction {
    margin-bottom: 20px;
}

.sentence {
    margin-left: 20px;
}

.sentence .original {
    font-style: italic;
}

.sentence .corrected {
    color: green;
}

.sentence .commentary {
    color: #999;
}
</style>
{% extends 'langCorrect/base.html' %}
{% block content %}
    <div class="post">
        <div class="head">
            <a href="{% url 'profile' post.author.username %}" class="author">{{ post.author.username }}</a>
            <p class="timestamp">{{ post.creation_timestamp | date:"j F Y г." }}</p>
        </div>
        <div class="body">
            <h2 class="title">{{ post.verbose_title }}</h2>
            <p class="text">{{ post.text }}</p>
        </div>
        <div class="footer">
            <span class="language">{{ post.language }}</span>
            <span class="corrections">{{ post.correctionsQuantity }}</span>
            <a href="{% url 'corrections' post.title %}" class="correct">Исправить</a>
        </div>
    </div>
    <div class="corrections">
        <h3>Исправления</h3>
        {% for correction in post.correction_set.all %}
        <div class="correction">
            <div class="author">{{ correction.author }}</div>
            {% for sentence in correction.sentence_set.all %}
            <div class="sentence">
                <div class="original">Изначальное предложение: {{ sentence.original }}</div>
                {% if sentence.isCorrect %}
                <div class="corrected">Все правильно</div>
                {% else %}
                <div class="corrected">Исправленная версия: {{ sentence.text }}</div>
                {% endif %}
                {% if sentence.commentary %}
                <div class="commentary">Замечание: {{ sentence.commentary }}</div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
{% endblock content %}

langCorrect/templates/langCorrect/post_form.html
<style>
    .my-form {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    background-color: #f9f9f9;
}

/* Стили для кнопки "Сохранить" */
.my-button {
    display: inline-block;
    padding: 10px 20px;
    font-size: 16px;
    border: none;
    border-radius: 5px;
    background-color: #007bff;
    color: #fff;
    text-align: center;
    text-decoration: none;
    cursor: pointer;
    transition: background-color 0.3s;
}

.my-button:hover {
    background-color: #0056b3;
}
</style>
{% extends 'langCorrect/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST" class="my-form">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary my-button">Сохранить</button>
    </form>
{% endblock content %}

langCorrect/templates/langCorrect/profile.html
{% extends 'langCorrect/base.html' %}
{% block content %}
<div style = 'display: flex'>
    <div >
        <div>{{ user.username }}</div>
        <div>
            <div>Языки</div>
            {% for language in languages %}
            <div>{{ language.language }} ({{ language.level }})</div>
            {% endfor %}
        </div>
        <div>
            <div><button>Языки</button></div>
            <div><button>Пароль</button></div>
        </div>
    </div>
    <div>
        {% for post in posts %}
        <div class="post">
            <div class="post-head">
                <a href="{% url 'profile' post.author.username %}" class="author">{{ post.author.username }}</a>
                <p class="timestamp">{{ post.creation_timestamp | date:"j F Y г." }}</p>
            </div>
            <div class="post-body">
                <h2 class="title">{{ post.verbose_title }}</h2>
                <h2 class="title">{{ post.title }}</h2>
                <p class="content">{{ post.text }}</p>
            </div>
            <div class="post-footer">
                <span class="language">{{ post.language }}</span>
                <span class="corrections">Число исправлений: {{ post.correctionsQuantity }}</span>
                <a href="{% url 'corrections' post.title %}" class="correct-link">Исправить</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content%}

langCorrect/templates/langCorrect/signup.html
{% extends 'langCorrect/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ language_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock content %}